CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    email VARCHAR(255) NOT NULL,

    password_hash VARCHAR(255) NOT NULL,

    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT uk_users_email
        UNIQUE (email)
);


CREATE TABLE files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    original_name VARCHAR(255) NOT NULL,

    storage_name VARCHAR(255) NOT NULL,

    content_type VARCHAR(255),

    size BIGINT NOT NULL,

    download_token VARCHAR(255) NOT NULL,

    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,

    expires_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,

    owner_id BIGINT NOT NULL,


    CONSTRAINT uk_files_storage_name
        UNIQUE (storage_name),

    CONSTRAINT uk_files_download_token
        UNIQUE (download_token),

    CONSTRAINT fk_files_owner
        FOREIGN KEY (owner_id)
        REFERENCES users(id)
);