spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/datashare
spring.datasource.username=datashare
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
jwt.secret=${JWT_SECRET}

# Structured logs
logging.file.name=logs/datashare.log
logging.structured.format.file=logstash
